title = "PT Women in Tech"
baseurl = "http://example.org/"
languageCode = "en-us"
theme = "mz_hugo"
contentdir = "content"
MetaDataFormat = "yaml"
googleAnalytics = ""
[taxonomies]
  tag = "tags"
[blackfriday]
  hrefTargetBlank = true