title: "PT Women in Tech"
baseurl: ""
languageCode: "en-us"
theme: "mz_hugo"
contentdir: "content"
MetaDataFormat: "yaml"
googleAnalytics: ""
taxonomies:
  tag: "tags"
blackfriday:
  hrefTargetBlank: true